version: '3.1'

services:
    phpserver:
        image: phpserver
        container_name: phpserver
        build:
            context: ./php
        restart: always
        depends_on:
            - mercure
        volumes:
            - ../:/srv/app
    mercure:
        image: dunglas/mercure
        restart: unless-stopped
        environment:
            SERVER_NAME: ':80' # disables HTTPS
            MERCURE_PUBLISHER_JWT_KEY: 'aVerySecretKey'
            MERCURE_SUBSCRIBER_JWT_KEY: 'aVerySecretKey'
        command: /usr/bin/caddy run -config /etc/caddy/Caddyfile.dev # enable the development mode
        ports:
            - "3000:80"
        volumes:
            - caddy_data:/data
            - caddy_config:/config

volumes:
    caddy_data:
    caddy_config:
