version: '3.1'

services:
    phpserver:
        image: phpserver
        container_name: phpserver
        build:
            context: ./php
        restart: always
        depends_on:
            - mercure
        volumes:
            - ../:/srv/app
    mercure:
        image: dunglas/mercure
        environment:
            - JWT_KEY=aVerySecretKey
        ports:
            - 3000:80
        labels:
            - traefik.frontend.rule=Host:localhost
