name: CI
on: [push]

jobs:
    unit_tests_php72:
        name: Unit tests PHP 7.4
        runs-on: ubuntu-latest
        container: php:7.4
        steps:
            -   uses: actions/checkout@v1
            -   uses: docker://composer:2
                with:
                    args: composer install --no-ansi --no-progress
            -   run: ./vendor/bin/phpunit --coverage-clover=build/coverage.xml --testsuite unit-tests
            -   uses: codecov/codecov-action@v1
                with:
                    file: ./build/coverage.xml
                    token: ${{secrets.CODECOV_TOKEN}}
                    flags: unittests
    PSR12_code_style:
        name: PSR 12 Codestyle checks
        runs-on: ubuntu-latest
        container: php:7.4
        steps:
            -   uses: actions/checkout@v1
            -   uses: docker://composer:2
                with:
                    args: composer install --no-ansi --no-progress
            -   run: ./vendor/bin/phpcs --standard=PSR12 src
    Static_analysis:
        name: Static analysis checks
        runs-on: ubuntu-latest
        container: php:7.4
        steps:
            -   uses: actions/checkout@v1
            -   uses: docker://composer:2
                with:
                    args: composer install --no-ansi --no-progress
            -   run: vendor/bin/phpstan analyse -l 6 src tests
    functional_tests_php74:
        name: Functional tests PHP 7.4
        runs-on: ubuntu-latest
        container: php:7.4
        services:
            mercure:
                image: dunglas/mercure
                env:
                    MERCURE_PUBLISHER_JWT_KEY: aVerySecretKey
                    MERCURE_SUBSCRIBER_JWT_KEY: aVerySecretKey
        steps:
            -   uses: actions/checkout@v1
            -   uses: docker://composer:2
                with:
                    args: composer install --no-ansi --no-progress
            -   run: ./vendor/bin/phpunit --testsuite functional-tests